name: Terraform CI/CD (OIDC - Dev)

on:
  pull_request:
    branches:
      - main
    paths:
      - "modules/**"
      - "environments/dev/**"

  push:
    branches:
      - main
    paths:
      - "modules/**"
      - "environments/dev/**"

permissions:
  id-token: write      # REQUIRED for AWS OIDC
  contents: read
  pull-requests: write # Optional: PR comments

concurrency:
  group: terraform-dev
  cancel-in-progress: false

jobs:
  terraform:
    name: Terraform Pipeline (Dev)
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        working-directory: environments/dev

    steps:
      # -----------------------------
      # Checkout
      # -----------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------
      # AWS OIDC Auth
      # -----------------------------
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/Iacc_githhub_actions_role
          aws-region: ${{ vars.AWS_REGION }}

      # -----------------------------
      # Terraform Setup
      # -----------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          terraform_wrapper: false

      - name: Verify Terraform Version
        run: terraform version

      # -----------------------------
      # Terraform Quality Checks
      # -----------------------------
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      # -----------------------------
      # Terraform Plan
      # -----------------------------
      - name: Terraform Plan
        run: terraform plan -input=false -var-file="terraform.tfvars" -out=tfplan

